export const uomList = [
  { uom_code: "001", description: "Numbers" },
  { uom_code: "002", description: "Pieces" },
  { uom_code: "003", description: "Units" },
  { uom_code: "004", description: "Kilograms" },
  { uom_code: "005", description: "Litres" },
  { uom_code: "006", description: "Meters" },
  { uom_code: "007", description: "Boxes" },
  { uom_code: "008", description: "Dozens" },
  { uom_code: "009", description: "Packets" },
  { uom_code: "010", description: "Pairs" },
  { uom_code: "011", description: "Rolls" },
  { uom_code: "012", description: "Bags" },
  { uom_code: "013", description: "Sets" },
  { uom_code: "014", description: "Cartons" },
  { uom_code: "015", description: "Tons" },
  { uom_code: "016", description: "Grams" },
  { uom_code: "017", description: "Packets (Small)" },
  { uom_code: "018", description: "Bundles" },
  { uom_code: "019", description: "Cans" },
  { uom_code: "020", description: "Gallons" },
];
